### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by ryw** [gandev/meteor-server-console#1]
- Font size is larger than Chrome console
- Resize (cmd-+) doesn't have an efffect like it does for Chrome console (not sure if this is inherent issue w/ Chrome extensions)

**Comment by gandev** [comment]
i adjusted the font size a little bit more towards Chrome Console in v0.3. But i have no idea, at the moment, how to make (cmd-+) work... but it's not a big problem for me because it scales when you switch to Chrome Console to do that.
